.\" man page for the ppasskeeper utility
.\"
.\" Denis Martinez: initial version (20080911)
.\" Martin PERES: update to rc1 version (20090330)

.TH ppasskeeper 1 "March 2009" "Portable Password Keeper" "A modular password manager"

.SH NAME
.P
ppasskeeper - password management utility

.SH SYNOPSIS
.P
\fBppasskeeper\fR -L [-u PPK_PASSWORD]
.br
\fBppasskeeper\fR -G -m MODULE -t app|net|item -k KEY [-u PPK_PASSWORD]
.br
\fBppasskeeper\fR -S -m MODULE -t app|net|item -k KEY [-p PASSWORD -u PPK_PASSWORD]
.br

.SH DESCRIPTION
.P
List the available methods (modules) for getting/storing passwords through the ppasskeeper library.
.TP
\fB-L\fR
Shows a list of modules with a short description for each one.
.P
Get or set a password associated to a particular resource.
.TP
\fB-G\fR
Get a password and display it.
.TP
\fB-S\fR
Set a password.
.P
One of the actions \fB-L\fR, \fB-G\fR, or \fB-S\fR must be specified on the command-line.

.SS MODULES
.P
A module is an interface that manages passwords either by using a particular keyring (system-dependent), or a portable interface.
.br
A list of common modules is available below.
.TP
\fB-m \fIMODULE\fR
Specifies which module to use.
.TP
\fBAsk_For_Pass_Qt\fR
Prompt the password through a Qt Dialog.
.TP
\fBAsk_For_Pass_GTK\fR
Prompt the password through a GTK Dialog.
.TP
\fBAsk_For_Pass_WIN32\fR
Prompt the password through a Windows Dialog.
.TP
\fBKWallet\fR
Use the KDE4 Wallet.
.TP
\fBSave_To_File_Enc\fR
Store passwords with a stupid encryption scheme (to make passwords unreadable at the first look).
.TP
\fBSave_To_File_PT\fR
Store passwords as plain text.
.TP
\fBSaveToRegistry\fR
Store passwords in the Windows registry.

.SS RESOURCES
.P
Some modules make it possible to store passwords in a particular fashion, depending on the type of resource.
.P
If the module does not have this possibility, ppasskeeper will fall back on a way that is more conventional.
.TP
\fB-t\fR
\fIapp\fR|\fInet\fR|\fIitem\fR
.P
Resource types:
.TP
\fBApplication\fR
An application, specified by its name, and a user name.
.TP
\fBNetwork\fR
A network service, specified by a host name, a user name, and a port number.
.TP
\fBItem\fR
A resource with just an identifier which name is chosen by the user.

.SS KEYS
.P
A key identifies a password entry, using a string format that depends on the resource type.
.TP
\fB-k \fIKEY\fR
.P
Key formats:
.TP
\fBApplication key\fR
\fIAPPLICATION_NAME\fR:\fIUSER_NAME\fR
.TP
\fBNetwork key\fR
\fIUSER_NAME\fR@\fIHOST_NAME\fR:\fIPORT\fR
.TP
\fBItem key\fR
\fIITEM_NAME\fR

.SS PASSWORD
.P
When setting a password, it can be specified either on the command-line, or interactively on the terminal.
.TP
\fB-p \fIPASSWORD\fR
Specify the password as an argument.

.SS PPK_PASSWORD
.P
When the library is locked, you need to set-up PPK_PASSWORD to unlock it.
.TP
\fB-u \fIPPK_PASSWORD\fR
Specify the ppk's password as an argument.

.SH AUTHORS
.P
Written by Denis Martinez, Martin Peres.

.SH COPYRIGHT
.P
LGPLv2 or later <http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html>.
