.\" man page for the ppasskeeper utility
.\"
.\" Denis Martinez: initial version (20080911)
.\" Martin PERES: update to beta2 version (20090419)

.TH ppasskeeper 1 "April 2009" "Portable Password Keeper" "A modular password manager"

.SH NAME
.P
ppasskeeper - password management utility

.SH SYNOPSIS
.P
\fBppasskeeper\fR -L [-u PPK_PASSWORD]
.br
\fBppasskeeper\fR -G -m MODULE -t app|net|item -k KEY [-f file -u PPK_PASSWORD]
.br
\fBppasskeeper\fR -G -m MODULE -l ani [-f file -u PPK_PASSWORD]
.br
\fBppasskeeper\fR -S -m MODULE -t app|net|item -k KEY [-f file -p PASSWORD -u PPK_PASSWORD]
.br
\fBppasskeeper\fR -R -m MODULE -k KEY [-u PPK_PASSWORD]
.br
\fBppasskeeper\fR -W -m MODULE -k KEY -p VALUE [-u PPK_PASSWORD]
.br
\fBppasskeeper\fR -D [-m MODULE -u PPK_PASSWORD]
.br

.SH DESCRIPTION
.P
List the available methods (modules) for getting/storing passwords through the ppasskeeper library.
.TP
\fB-L\fR
Shows a list of modules with a short description for each one.
.P
Access the library in Read or Write mode.
.TP
\fB-G\fR
Get an entry and display it or list the entries of a particular module.
.TP
\fB-S\fR
Set a password.
.TP
\fB-R\fR
Read a parameter.
.TP
\fB-W\fR
Write a parameter.
.P
One of the actions \fB-L\fR, \fB-G\fR, or \fB-S\fR must be specified on the command-line.

.SS MODULES
.P
A module is an interface that manages passwords either by using a particular keyring (system-dependent), or a portable interface.
.br
A list of common modules is available below.
.TP
\fB-m \fIMODULE\fR
Specifies which module to use.
.TP
\fBAsk_For_Pass_Qt\fR
Prompt the password through a Qt Dialog.
.TP
\fBAsk_For_Pass_GTK\fR
Prompt the password through a GTK Dialog.
.TP
\fBAsk_For_Pass_WIN32\fR
Prompt the password through a Windows Dialog.
.TP
\fBKWallet\fR
Use the KDE4 Wallet.
.TP
\fBGKeyring\fR
Use the Gnome Keyring.
.TP
\fBSave_To_File_Enc\fR
Store passwords with a simple encryption scheme (to make passwords unreadable at first glance).
.TP
\fBSave_To_File_PT\fR
Store passwords as plain text.
.TP
\fBSaveToRegistry\fR
Store passwords in the Windows registry.

.SS DEFAULT MODULES
.P
You can set up a default module by using the 'D' mode combined with the 'm' option. 
If you don't provide the 'm' option, you'll get the default value.
.P
Parameters :
.TP
\fB-m \fIMODULE\fR
Specifies which module to use as default.
.TP
That's all folk.

.SS LISTING
.P
Some modules enable you to list their entries.
.P
You should use the -G mode with :
.TP
\fB-l\fR
\fIa\fR|\fIn\fR|\fIi\fR
.P
Resource types:
.TP
\fBa\fR
List the application entries.
.TP
\fBn\fR
List the network entries.
.TP
\fBi\fR
List the item entries.
.P
The types can be combined.

.SS PARAMETERS
.P
Some modules may need some parameters to run. You can set them using this interface.
To set up or read a parameter, you'll need at least a module id (-m) and a key name (-k).

.TP
\fBWriting\fR
ppasskeeper -W -m "module_id" -k "key_name" -p "my value"

.TP
\fBReading :\fR
ppasskeeper -R -m "module_id" -k "key_name"


.SS RESOURCES
.P
Some modules make it possible to store passwords in a particular fashion, depending on the type of resource.
.P
If the module does not have this possibility, ppasskeeper will fall back on a way that is more conventional.
.TP
\fB-t\fR
\fIapp\fR|\fInet\fR|\fIitem\fR
.P
Resource types:
.TP
\fBApplication\fR
An application, specified by its name, and a user name.
.TP
\fBNetwork\fR
A network service, specified by a host name, a user name, and a port number.
.TP
\fBItem\fR
A resource with just an identifier which name is chosen by the user.

.SS KEYS
.P
A key identifies a password entry, using a string format that depends on the resource type.
.TP
\fB-k \fIKEY\fR
.P
Key formats:
.TP
\fBApplication key\fR
\fIAPPLICATION_NAME\fR:\fIUSER_NAME\fR
.TP
\fBNetwork key\fR
\fIUSER_NAME\fR@\fIHOST_NAME\fR:\fIPORT\fR
.TP
\fBItem key\fR
\fIITEM_NAME\fR

.SS PASSWORD
.P
When setting a password, it can be specified either on the command-line, or interactively on the terminal.
.TP
\fB-p \fIPASSWORD\fR
Specify the password as an argument. You can also store a file, see the -f option.

.SS FILE
.P
When setting or getting a password, you can choose to save/read to/from a file.
.TP
\fB-f \fIFILEPATH\fR
Specify the file path as an argument. You can also store a string, see the -p option.

.SS PPK_PASSWORD
.P
When the library is locked, you need to set-up PPK_PASSWORD to unlock it.
.TP
\fB-u \fIPPK_PASSWORD\fR
Specify the ppk's password as an argument.

.SH AUTHORS
.P
Written by Denis Martinez, Martin Peres.

.SH COPYRIGHT
.P
LGPLv2 or later <http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html>.
